### ISSUE TITLE
Compilation error on MVC.Core project

### ISSUE THREAD

**Issue by xavehoo** [DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908#21]
Hi, if I try to compile the MCV.Core project, it return me a CS1061 error ('ControllerDataSourceOptionsBuilder' does not contain a definition for 'OnLoaded' and no accessible extension method accepting a first argument of type 'ControllerDataSourceOptionsBuilder').
My IDE is Visual Studio Professional 2019 - v16.3.10

**Comment by AndreyKozhevnikov** [comment]
Hello,

To get rid of this issue, use one of the following steps:

* if you have v19.2.4, use our updated '19.2.4+' branch: [DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908: .NET, .NET Core, Frameworks (XAF & XPO), eXpressApp Framework](https://github.com/DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908)
* in case you need v19.1, update the [MVC.Core/CS/AspNetCoreMvcApplication.csproj](https://github.com/DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908/blob/19.1.4%2B/ASP.NET/MVC.Core/CS/AspNetCoreMvcApplication.csproj) file so that it refers to the exact version you have (e.g. 19.1.8) instead of the default one for all DevExpress libraries:


```

<PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="19.1.*" />
<PackageReference Include="DevExpress.Persistent.BaseImpl" Version="19.1.*" />
<PackageReference Include="DevExtreme.AspNet.Core" Version="19.1.*" />


```
Let us know in case of any further difficulties.

Thanks,
Andrey
