### ISSUE TITLE
Incorrect password on authentication

### ISSUE THREAD

**Issue by xavehoo** [DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908#32]
Hi,
I integrated the ASP.NET Core MVC version in a project, where the db is MariaDb, but if I try to authenticate with password, it gave me an "incorrect credential" error. If I use the password "as it is" stored in the database (hashed), it work.

**Comment by AndreyKozhevnikov** [comment]
Hello,

We have the following note in the [readme](https://github.com/DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908/tree/19.2.6%2B/ASP.NetCore/MVC?utm_source=DevExpress&utm_medium=Website&utm_campaign=XAF&utm_content=XAF_Security_NonXAF_Series_5_MVC_Core) file:

"Make sure that the static EnableRfc2898 and SupportLegacySha512 properties in your non-XAF application have the same values as in the XAF application where passwords were set. Otherwise you won't be able to login."

Please perform this step to get rid of the issue you faced. If it doesn't help, create a ticket in our [Support Center](https://supportcenter.devexpress.com/ticket/list) and provide us with a simple example that illustrates this behavior in action.

Thanks,
Andrey
